spring.application.name=suculentas

# Puerto en el que correrá la app Spring Boot
server.port=8080

# Conexión a la Base de Datos local en MySQL (Verifica si usas puerto 3306 o 3307)
spring.datasource.url=jdbc:mysql://localhost:3306/suculentasProyecto?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Alex12345ITQ

# Estrategia de Hibernate: 'update' creará o actualizará las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dialecto estándar de Hibernate (Compatible con tu versión moderna de Spring Boot)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración crucial para que las cookies mantengan tu sesión activa en el navegador
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

# Desactivar la caché de plantillas para desarrollo en vivo
spring.thymeleaf.cache=false
